version: "3"

services:
  flask:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
  redis:
    image: redis
    command: ["--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
